apiVersion: v1
kind: Service
metadata:
  name: {{ include "tau.fullname" . }}
  labels:
    {{- include "tau.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tau
      protocol: TCP
      name: tau
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "tau.selectorLabels" . | nindent 4 }}
