base_url = "https://tau.bxrne.com"
title = "tau"
description = "A time-series database built on immutable, layered temporal intervals."
default_language = "en"
theme = "zerm"
compile_sass = true
build_search_index = true
taxonomies = [
           {name = "tags"},
           {name = "categories"},
]

[extra]
author = "Adam Byrne"
show_author = false
show_categories = true
show_tags = true
theme_color = "orange"
show_menu_items = 3
custom_css = true

full_width = false
center = true

# favicon = ""
# og_preview_img = ""


copyright = "Copyright Adam Byrne"
logo_text = "tau"
logo_home_link = ""
main_menu = [
          {url="/docs/overview/", name="Overview"},
          {url="/docs/how-it-works/", name="How it works"},
          {url="/docs/tauql/", name="TauQL"},
          {url="/docs/dst/", name="DST"},
          {url="/docs/testing/", name="Testing"},
          {url="/docs/configuration/", name="Configuration"},
          {url="/docs/containers/", name="Containers"},
          {url="/docs/benchmarks/", name="Benchmarks"},
]

menu_more = "show more"
read_more = "read more"
read_other_posts = "read other posts"
enable_katex = false
disqus = { enabled=false, short_name="" }
ToC = true
